
version: '3.7'

# Define services
services:
  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: polls
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      backend :
         ipv4_address: 10.0.5.30 


# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.5.0/24
         gateway: 10.0.5.1
